git submodule add https://github.com/bhlzlx/CMCore thirdpart/CMCore
git submodule add https://github.com/bhlzlx/CMUtil thirdpart/CMUtil
git submodule add https://github.com/bhlzlx/CMPlatform thirdpart/CMPlatform
git submodule add https://github.com/bhlzlx/CMAssetsManage thirdpart/CMAssetsManage
git submodule add https://github.com/bhlzlx/CM2D thirdpart/CM2D
git submodule add https://github.com/bhlzlx/CMSceneGraph thirdpart/CMSceneGraph
git submodule add https://github.com/bhlzlx/ShaderMaker thirdpart/ShaderMaker
git submodule add https://github.com/bhlzlx/CMCMakeModule thirdpart/CMCMakeModule
git submodule add https://github.com/bhlzlx/CMAudio thirdpart/CMAudio
git submodule add https://github.com/juj/MathGeoLib thirdpart/MathGeoLib